### ISSUE TITLE
ValidateAndGetData throws SecureToken Expired although ttl is set to null

### ISSUE THREAD

**Issue by jpvdm1** [fdipuma/simpletoken#3]
Hi,

I tested the new functionality and it seems to throw a "SecureToken Expired" exception although the ttl is set to null.

Steps to replicate:

1. Generate Token with ttl set to null
2. Sleep for more than 1 minute
3. ValidateAndGetData against generated Token from step 1

Kind Regards,
JP

**Comment by fdipuma** [comment]
Can you confirm this happens only when generating the Token using the extension method which takes any object as argument? It should work as expected when passing a dictionary.

If this is the case I will push a fix as soon as possible.

**Comment by jpvdm1** [comment]
Works fine with Dictionary, doesn't work with Anonymous object: 

`encProvider.GenerateToken(new { UserId = 12 }, ttl: null); `
